# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cartesian_to_polar_rcpp <- function(cartesian, anchor, threads = 1L) {
    .Call(`_rTLS_cartesian_to_polar_rcpp`, cartesian, anchor, threads)
}

circleRANSAC_rcpp <- function(cloud, fpoints, z_value, poutlier, max_iterations, threads = 1L) {
    .Call(`_rTLS_circleRANSAC_rcpp`, cloud, fpoints, z_value, poutlier, max_iterations, threads)
}

euclidean_rcpp <- function(sample, base, threads = 1L) {
    .Call(`_rTLS_euclidean_rcpp`, sample, base, threads)
}

features_knn_rcpp <- function(index, query, k, threads = 1L, progress = TRUE) {
    .Call(`_rTLS_features_knn_rcpp`, index, query, k, threads, progress)
}

features_radius_rcpp <- function(index, query, radius, threads = 1L, progress = TRUE) {
    .Call(`_rTLS_features_radius_rcpp`, index, query, radius, threads, progress)
}

knn_rcpp <- function(query, ref, k, same, build, threads, checks) {
    .Call(`_rTLS_knn_rcpp`, query, ref, k, same, build, threads, checks)
}

line_AABB_rcpp <- function(orig, end, AABB_min, AABB_max) {
    .Call(`_rTLS_line_AABB_rcpp`, orig, end, AABB_min, AABB_max)
}

lines_interception_rcpp <- function(orig, end, voxels, edge_length, threads = 1L, progress = TRUE) {
    .Call(`_rTLS_lines_interception_rcpp`, orig, end, voxels, edge_length, threads, progress)
}

meanDis_knn_rcpp <- function(amat, k, threads = 1L, progress = TRUE) {
    .Call(`_rTLS_meanDis_knn_rcpp`, amat, k, threads, progress)
}

polar_to_cartesian_rcpp <- function(polar, threads = 1L) {
    .Call(`_rTLS_polar_to_cartesian_rcpp`, polar, threads)
}

radius_search_rcpp <- function(query, ref, radius, max_neighbour, same, build, threads, checks) {
    .Call(`_rTLS_radius_search_rcpp`, query, ref, radius, max_neighbour, same, build, threads, checks)
}

rotate2D_rcpp <- function(plane, angle, threads = 1L) {
    .Call(`_rTLS_rotate2D_rcpp`, plane, angle, threads)
}

rotate3D_rcpp <- function(cloud, roll, pitch, yaw, threads = 1L) {
    .Call(`_rTLS_rotate3D_rcpp`, cloud, roll, pitch, yaw, threads)
}

voxelization_rcpp <- function(cloud, edge_length, threads = 1L) {
    .Call(`_rTLS_voxelization_rcpp`, cloud, edge_length, threads)
}

