# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cartesian_to_polar_rcpp <- function(cartesian, anchor) {
    .Call('_rTLS_cartesian_to_polar_rcpp', PACKAGE = 'rTLS', cartesian, anchor)
}

dimensionality_rcpp <- function(amat, bmat, radius, threads = 1L) {
    .Call('_rTLS_dimensionality_rcpp', PACKAGE = 'rTLS', amat, bmat, radius, threads)
}

distanceC <- function(xcoor, ycoor, zcoor, X, Y, Z) {
    .Call('_rTLS_distanceC', PACKAGE = 'rTLS', xcoor, ycoor, zcoor, X, Y, Z)
}

euclidean_distance <- function(sample, base) {
    .Call('_rTLS_euclidean_distance', PACKAGE = 'rTLS', sample, base)
}

polar_to_cartesian_rcpp <- function(polar) {
    .Call('_rTLS_polar_to_cartesian_rcpp', PACKAGE = 'rTLS', polar)
}

rotate_rcpp <- function(cloud, roll, pitch, yaw) {
    .Call('_rTLS_rotate_rcpp', PACKAGE = 'rTLS', cloud, roll, pitch, yaw)
}

